
apiVersion: v1
kind: Service
metadata:
  name: cluster-cni-wh-hack-webhook
spec:
  ports:
    - port: 9443
      targetPort: validating-hook
      protocol: TCP
  selector:
    control-plane: cluster-cni-wh-hack
  type: ClusterIP
